### ISSUE TITLE
Example throwing sqlite3.OperationalError

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [opendifferentialprivacy/smartnoise-sdk#321]
I'm trying to run the basic example in the README from https://github.com/opendifferentialprivacy/smartnoise-sdk, and I am getting this error. I'm not sure what this means:

```
Traceback (most recent call last):
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1267, in _execute_context
    cursor, statement, context
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 596, in do_execute_no_params
    cursor.execute(statement)
sqlite3.OperationalError: near "(": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandasql/sqldf.py", line 61, in __call__
    result = read_sql(query, conn)
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 515, in read_sql
    chunksize=chunksize,
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1295, in read_query
    result = self.execute(*args)
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1162, in execute
    *args, **kwargs
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1267, in _execute_context
    cursor, statement, context
  File "/home/anubhav/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 596, in do_execute_no_params
    cursor.execute(statement)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT primary_key ) AS keycount, SUM ( petal_width__0_cm_1_ ) AS sum_petal_width__0_cm_1_, COUNT ( petal_width__0_cm_1_ ) AS count_petal_width__0_cm_1_ FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY primary_key ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT primary_key AS primary_key, CASE WHEN petal_width__0_cm_1_ < 0 THEN 0 WHEN petal_width__0_cm_1_ > 3 THEN 3 ELSE  petal_width__0_cm_1_ END AS petal_width__0_cm_1_ FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anubhav/cs860/smartnoise-sdk/example.py", line 21, in <module>
    rowset = execute_private_query(reader, schema, 0.3, 'SELECT AVG("petal width (cm)") FROM dbo.iris')
  File "/home/anubhav/.local/lib/python3.6/site-packages/opendp/smartnoise/sql/__init__.py", line 34, in execute_private_query
    rowset = PrivateReader(reader, schema, budget).execute(query)
  File "/home/anubhav/.local/lib/python3.6/site-packages/opendp/smartnoise/sql/private_reader.py", line 154, in execute
    return self._execute_ast(query)
  File "/home/anubhav/.local/lib/python3.6/site-packages/opendp/smartnoise/sql/private_reader.py", line 214, in _execute_ast
    db_rs = self._get_reader(subquery)._execute_ast(subquery)
  File "/home/anubhav/.local/lib/python3.6/site-packages/opendp/smartnoise/sql/reader/base.py", line 19, in _execute_ast
    return self.execute(query_string)
  File "/home/anubhav/.local/lib/python3.6/site-packages/opendp/smartnoise/sql/reader/pandas.py", line 107, in execute
    q_result = sqldf(clean_query(query), locals())
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandasql/sqldf.py", line 156, in sqldf
    return PandaSQL(db_uri)(query, env)
  File "/home/anubhav/.local/lib/python3.6/site-packages/pandasql/sqldf.py", line 63, in __call__
    raise PandaSQLException(ex)
pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT primary_key ) AS keycount, SUM ( petal_width__0_cm_1_ ) AS sum_petal_width__0_cm_1_, COUNT ( petal_width__0_cm_1_ ) AS count_petal_width__0_cm_1_ FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY primary_key ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT primary_key AS primary_key, CASE WHEN petal_width__0_cm_1_ < 0 THEN 0 WHEN petal_width__0_cm_1_ > 3 THEN 3 ELSE  petal_width__0_cm_1_ END AS petal_width__0_cm_1_ FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by SrivastavaAnubhav** [comment]
Putting the query into eversql's validator, it looks like there's a syntax error somewhere (but it's generated and I'm not sure where)

**Comment by joshua-oss** [comment]
I think this was due to an incompatibility with SQLite in Python 3.6.  The version of SQLite is older, and didn't support COUNT DISTINCT, which we need for differential privacy processing.

Can you verify by trying in a newer Python environment?  We like the SQLite version that is included with anaconda/miniconda.

**Comment by SrivastavaAnubhav** [comment]
I upgraded to python 3.8 and this is the new error I'm getting:
```
Traceback (most recent call last):
  File "/home/anubhav/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anubhav/cs860/smartnoise-sdk/example.py", line 22, in <module>
    df = pd.DataFrame(rowset[1:], columns=rowset[0])
  File "/home/anubhav/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/anubhav/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

**Comment by joshua-oss** [comment]
Oh!  That's because we changed `execute_private_reader` to return a Pandas DataFrame, but we forgot to update the sample.  The sample is trying to convert the DataFrame to a DataFrame using array slicers.

Can you verify that the below snippet works?  We will update the sample;  thanks for reporting this.

```
import sklearn.datasets
import pandas as pd

from opendp.smartnoise.sql import execute_private_query, PandasReader
from opendp.smartnoise.metadata import CollectionMetadata
from opendp.smartnoise.metadata.collection import Table, Float

sklearn_dataset = sklearn.datasets.load_iris()
sklearn_df = pd.DataFrame(data=sklearn_dataset.data, columns=sklearn_dataset.feature_names)


iris = Table("dbo", "iris", [
    Float("sepal length (cm)", 4, 8),
    Float("sepal width (cm)", 2, 5),
    Float("petal length (cm)", 1, 7),
    Float("petal width (cm)", 0, 3)
], 150)
schema = CollectionMetadata([iris], "csv")

reader = PandasReader(sklearn_df, schema)
df = execute_private_query(reader, schema, 0.3, 'SELECT AVG("petal width (cm)") AS petal FROM dbo.iris')
with pd.option_context('display.max_rows', None, 'display.max_columns', 3): print(df)
```

**Comment by SrivastavaAnubhav** [comment]
Great! I now see this, which I think seems correct:
```
      petal
0  1.799812
```
Feel free to close if this looks good to you. Thanks for working through this with me!
